In [1]:
import torch

In [2]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [5]:
torch.tensor([1,2,3,4], dtype=float, requires_grad=True)

tensor([1., 2., 3., 4.], dtype=torch.float64, requires_grad=True)

In [18]:
torch.tensor([1,2,3,4], dtype=float, requires_grad=True)

tensor([1., 2., 3., 4.], dtype=torch.float64, requires_grad=True)

In [19]:
t1 = torch.tensor([1,2,3,4], dtype=float, requires_grad=True)

In [21]:
t1.to("cpu")

tensor([1., 2., 3., 4.], dtype=torch.float64, requires_grad=True)

In [22]:
import numpy

In [23]:
a = numpy.array([1, 2, 3])

In [24]:
t = torch.from_numpy(a)

In [25]:
t

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
a[1] = 0

In [27]:
t

tensor([1, 0, 3], dtype=torch.int32)

## This is about random

In [28]:
torch.zeros([1, 5], out=None)

tensor([[0., 0., 0., 0., 0.]])

In [29]:
torch.zeros((1, 5), out=None)

tensor([[0., 0., 0., 0., 0.]])

In [38]:
torch.zeros_like(torch.tensor([[1,2,3,], [4,5,6], [7,8,9]]))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])